# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id.setGeometry(QtCore.QRect(100, 60, 280, 21))
        self.id.setObjectName("id")
        self.name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(100, 90, 280, 21))
        self.name.setObjectName("name")
        self.roasting = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roasting.setGeometry(QtCore.QRect(100, 120, 280, 21))
        self.roasting.setObjectName("roasting")
        self.grounds = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.grounds.setGeometry(QtCore.QRect(100, 150, 280, 21))
        self.grounds.setObjectName("grounds")
        self.taste = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.taste.setGeometry(QtCore.QRect(100, 180, 280, 21))
        self.taste.setObjectName("taste")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 60, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 60, 16))
        self.label_6.setObjectName("label_6")
        self.price = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.price.setGeometry(QtCore.QRect(100, 210, 280, 21))
        self.price.setObjectName("price")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 60, 16))
        self.label_7.setObjectName("label_7")
        self.size = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.size.setGeometry(QtCore.QRect(100, 240, 280, 21))
        self.size.setObjectName("size")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 280, 160, 32))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 30, 300, 16))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "id"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Roasting"))
        self.label_4.setText(_translate("MainWindow", "Taste"))
        self.label_5.setText(_translate("MainWindow", "Gr/in grns"))
        self.label_6.setText(_translate("MainWindow", "Price"))
        self.label_7.setText(_translate("MainWindow", "Size"))
        self.pushButton.setText(_translate("MainWindow", "Редактировать"))
        self.label_8.setText(_translate("MainWindow", "Редактирование осуществляется по id записи."))
