# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(25, 21, 751, 480))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edit.setGeometry(QtCore.QRect(25, 510, 130, 32))
        self.edit.setObjectName("edit")
        self.update = QtWidgets.QPushButton(parent=self.centralwidget)
        self.update.setGeometry(QtCore.QRect(180, 510, 130, 32))
        self.update.setObjectName("update")
        self.update_table = QtWidgets.QPushButton(parent=self.centralwidget)
        self.update_table.setGeometry(QtCore.QRect(330, 510, 130, 32))
        self.update_table.setObjectName("update_table")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.edit.setText(_translate("MainWindow", "Редактировать"))
        self.update.setText(_translate("MainWindow", "Добавить"))
        self.update_table.setText(_translate("MainWindow", "Обновить"))
